[package]
authors = ["xiangxn"]
edition = "2021"
name = "wormhole3-account-binding"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0", features = ["preserve_order"]}
